<!DOCTYPE html><html>
        <head>
        <title>pyslvs</title>
        <meta charset="utf-8">
<meta property="head" content="H2">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link href="https://fonts.googleapis.com/css?family=Quicksand:300,400,500,700,900" rel="stylesheet">
        <link rel="stylesheet" href="./../cmsimde/static/chimper/fonts/icomoon/style.css">
        <link rel="stylesheet" href="./../cmsimde/static/chimper/css/bootstrap.min.css">
        <link rel="stylesheet" href="./../cmsimde/static/chimper/css/magnific-popup.css">
        <link rel="stylesheet" href="./../cmsimde/static/chimper/css/jquery-ui.css">
        <link rel="stylesheet" href="./../cmsimde/static/chimper/css/owl.carousel.min.css">
        <link rel="stylesheet" href="./../cmsimde/static/chimper/css/owl.theme.default.min.css">
        <link rel="stylesheet" href="./../cmsimde/static/chimper/css/bootstrap-datepicker.css">
        <link rel="stylesheet" href="./../cmsimde/static/chimper/fonts/flaticon/font/flaticon.css">
        <link rel="stylesheet" href="./../cmsimde/static/chimper/css/aos.css">
        <link rel="stylesheet" href="./../cmsimde/static/chimper/css/style.css">
        <link rel="shortcut icon" href="./../cmsimde/static/favicons.png">
        
        <style type='text/css'>
            .site-section {
            background-color: #FFFF;
            padding: 40px 40px;
            }
            body > div > div.dropdown.open {
                display: block;
            }
        </style>
    
        <!-- <script src="./../cmsimde/static/jquery.js"></script> -->
        <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script> -->
        <script src="../cmsimde/static/chimper/js/jquery-3.3.1.min.js"></script>
        <link rel="stylesheet" href="./../cmsimde/static/tipuesearch/css/normalize.min.css">
        <script src="./../cmsimde/static/tipuesearch/tipuesearch_set.js"></script>
        <script src="tipuesearch_content.js"></script>
        <link rel="stylesheet" href="./../cmsimde/static/tipuesearch/css/tipuesearch.css">
        <script src="./../cmsimde/static/tipuesearch/tipuesearch.js"></script>
        <!-- for Wink3 客製化關閉 -->
        <!--
        <link rel="stylesheet" type="text/css" href="./../cmsimde/static/winkPlayer.css" />
        <script type="text/javascript" src="./../cmsimde/static/winkPlayer.js"></script>
        -->
        <script>
            /* original tipuesearch
            $(document).ready(function() {
                 $('#tipue_search_input').tipuesearch();
            });
            */
            // customed doSearch
            function doSearch() {
                $('#tipue_search_input').tipuesearch({
                    newWindow: true, 
                    minimumLength: 2,
                    wholeWords: false, // for search 中文
                });
            }
            $(document).ready(doSearch);
        </script>
        
<script type="text/javascript" src="./../cmsimde/static/syntaxhighlighter/shCore.js"></script>
<script type="text/javascript" src="./../cmsimde/static/syntaxhighlighter/shBrushBash.js"></script>
<script type="text/javascript" src="./../cmsimde/static/syntaxhighlighter/shBrushDiff.js"></script>
<script type="text/javascript" src="./../cmsimde/static/syntaxhighlighter/shBrushJScript.js"></script>
<script type="text/javascript" src="./../cmsimde/static/syntaxhighlighter/shBrushJava.js"></script>
<script type="text/javascript" src="./../cmsimde/static/syntaxhighlighter/shBrushPython.js"></script>
<script type="text/javascript" src="./../cmsimde/static/syntaxhighlighter/shBrushSql.js"></script>
<script type="text/javascript" src="./../cmsimde/static/syntaxhighlighter/shBrushHaxe.js"></script>
<script type="text/javascript" src="./../cmsimde/static/syntaxhighlighter/shBrushXml.js"></script>
<script type="text/javascript" src="./../cmsimde/static/syntaxhighlighter/shBrushPhp.js"></script>
<script type="text/javascript" src="./../cmsimde/static/syntaxhighlighter/shBrushPowerShell.js"></script>
<script type="text/javascript" src="./../cmsimde/static/syntaxhighlighter/shBrushLua.js"></script>
<script type="text/javascript" src="./../cmsimde/static/syntaxhighlighter/shBrushMojo.js"></script>
<script type="text/javascript" src="./../cmsimde/static/syntaxhighlighter/shBrushCpp.js"></script>
<script type="text/javascript" src="./../cmsimde/static/syntaxhighlighter/shBrushCss.js"></script>
<script type="text/javascript" src="./../cmsimde/static/syntaxhighlighter/shBrushCSharp.js"></script>
<script type="text/javascript" src="./../cmsimde/static/syntaxhighlighter/shBrushDart.js"></script>
<script type="text/javascript" src="./../cmsimde/static/syntaxhighlighter/shBrushRust.js"></script>
<link type="text/css" rel="stylesheet" href="./../cmsimde/static/syntaxhighlighter/css/shCoreDefault.css"/>
<script type="text/javascript">SyntaxHighlighter.all();</script>
<!-- 暫時不用
<script src="./../cmsimde/static/fengari-web.js"></script>
<script type="text/javascript" src="./../cmsimde/static/Cango-13v08-min.js"></script>
<script type="text/javascript" src="./../cmsimde/static/CangoAxes-4v01-min.js"></script>
<script type="text/javascript" src="./../cmsimde/static/gearUtils-05.js"></script>
-->
<!-- for Brython 暫時不用
<script src="https://scrum-3.github.io/web/brython/brython.js"></script>
<script src="https://scrum-3.github.io/web/brython/brython_stdlib.js"></script>
-->
<style>
img.add_border {
    border: 3px solid blue;
}
</style>

</head>
<body>
<div class='container'><nav>
        
    <div class="site-wrap">

    <div class="site-mobile-menu">
      <div class="site-mobile-menu-header">
        <div class="site-mobile-menu-close mt-3">
          <span class="icon-close2 js-menu-toggle"></span>
        </div>
      </div>
      <div class="site-mobile-menu-body"></div>
    </div>
    
            <header class="site-navbar py-4 bg-white" role="banner">
              <div class="container">
                <div class="row align-items-center">
                <h1>Pyslvs - planar mechanism simulation and synthesis</h1>
                <div class="pl-4">
                    <form>
                    <input type="text" placeholder="Search" name="q" id="tipue_search_input" pattern=".{2,}" title="At least 2 characters" required>
                    </form>
                </div>
                  <!-- <div class="col-11 col-xl-2">
                    <h1 class="mb-0 site-logo"><a href="index.html" class="text-black h2 mb-0">Pyslvs - planar mechanism simulation and synthesis</a></h1> 
                  </div>
                  -->
                  <div class="col-12 col-md-10 d-none d-xl-block">
                    <nav class="site-navigation position-relative text-right" role="navigation">
    <ul class='site-menu js-clone-nav mr-auto d-none d-lg-block'>
                        <li class="active has-children"><a href="index.html">Home</a>
                        <ul class="dropdown">
                            <li><a href="sitemap.html">SMap</a></li>
                            <li><a href="./../reveal/index.html">reveal</a></li>
                            <li><a href="./../blog/index.html">blog</a></li>
                        </ul>
                      </li>
                     <li><a href='About.html'>About</a><li class='has-children'><a href='Pyslvs-UI.html'>Pyslvs-UI</a><ul class='dropdown'><li><a href='pyslvs.html'>pyslvs</a><li><a href='Development.html'>Development</a><li><a href='Pyinstaller.html'>Pyinstaller</a></li></ul><li class='has-children'><a href='MCAD.html'>MCAD</a><ul class='dropdown'><li><a href='Solid Edge.html'>Solid Edge</a></li></ul><li class='has-children'><a href='Tasks.html'>Tasks</a><ul class='dropdown'><li class='has-children'><a href='Windows.html'>Windows</a><ul class='dropdown'><li><a href='MSYS2.html'>MSYS2</a><li><a href='GIT.html'>GIT</a><li><a href='Python.html'>Python</a><li><a href='SciTE.html'>SciTE</a></li></li></ul></ul><li class='has-children'><a href='References.html'>References</a><ul class='dropdown'><li><a href='Papers.html'>Papers</a><li><a href='Replit.html'>Replit</a></li>
                      </ul>
                </nav>
              </div>
              <div class="d-inline-block d-xl-none ml-md-0 mr-auto py-3" style="position: relative; top: 3px;"><a href="#" class="site-menu-toggle js-menu-toggle text-black"><span class="icon-menu h3"></span></a></div>
              </div>

            </div>
          </div>
          
        </header>
    <div id="tipue_search_content">MCAD << <a href='MCAD.html'>Previous</a> <a href='Tasks.html'>Next</a> >> Tasks<br /><h1>Solid Edge</h1>
<h4>SDK</h4>
<p>The Solid Edge SDK provides developers with a range of tools and resources to create custom applications that interact with the Solid Edge software. The SDK includes documentation that covers the Solid Edge API, which provides access to the core functionality of the software. This allows developers to automate tasks, such as creating and modifying parts and assemblies, generating drawings and reports, and performing simulations and analyses.<br/><br/>The SDK also includes sample code and libraries that demonstrate how to use the API and provide a starting point for developing custom applications. These resources can help developers get up and running quickly and reduce the time it takes to create a working application.<br/><br/>One of the key benefits of using the Solid Edge SDK is the ability to support collaborative mechanical design processes. By creating custom applications that integrate with other tools and systems used in the design process, developers can help improve communication and collaboration between team members. This can help reduce errors, improve efficiency, and speed up the design process.</p>
<p>For example, a developer could create an application that integrates Solid Edge with a project management tool. This could allow team members to share design data, track progress, and collaborate on tasks directly within the project management tool. This could help improve visibility into the design process and ensure that everyone is working from the same information.<br/><br/>Overall, the Solid Edge SDK provides developers with a powerful set of tools to create custom applications that extend the functionality of Solid Edge and improve its integration with other systems.</p>
<p><a href="https://docs.plm.automation.siemens.com/docs/se/2020/api/webframe.html">Solid Edge 2020 SDK (siemens.com)</a></p>
<p>如何透過 Python 重用 Windows TLB or OCX 等 DLL 動態連結程式庫</p>
<p>pywin32: pip install pywin32</p>
<p>就可以利用 python -m win32com.client.combrowse 瀏覽操作系統中的 COM 程式庫.</p>
<p>若要將 Solid Edge Type library 轉為 .py, 執行 python -m win32com.client.makepy -i</p>
<pre class="brush:js;auto-links:false;toolbar:false" contenteditable="false">Y:\&gt;python -m win32com.client.makepy -i
Solid Edge Geometry Type Library
 {3E2B3BE1-F0B9-11D1-BDFD-080036B4D502}, lcid=0, major=1, minor=0
 &gt;&gt;&gt; # Use these commands in Python code to auto generate .py support
 &gt;&gt;&gt; from win32com.client import gencache
 &gt;&gt;&gt; gencache.EnsureModule('{3E2B3BE1-F0B9-11D1-BDFD-080036B4D502}', 0, 1, 0)</pre>
<p>接著利用 Python 程式執行, 列出轉為 .py 後的 Type Library 所在位置:</p>
<pre class="brush:py;auto-links:false;toolbar:false" contenteditable="false">from win32com.client import gencache
 
geom_type_lib = gencache.EnsureModule('{3E2B3BE1-F0B9-11D1-BDFD-080036B4D502}', 0, 1, 0)
print(dir(geom_type_lib))
print(repr(geom_type_lib))</pre>
<p>執行後可以取得 Solid Edge Geometry Type Library 轉出 .py 後的檔案所在目錄:</p>
<p>&lt;module 'win32com.gen_py.3E2B3BE1-F0B9-11D1-BDFD-080036B4D502x0x1x0' from 'C:\\Users\\pj2023\\AppData\\Local\\Temp\\gen_py\\3.11\\3E2B3BE1-F0B9-11D1-BDFD-080036B4D502x0x1x0.py'&gt;</p>
<p>Python for Solid Edge API example:</p>
<pre class="brush:py;auto-links:false;toolbar:false" contenteditable="false">import win32com.client
import os
import random
import string
  
def password_generator(size=4, chars=string.ascii_lowercase + string.digits):
  
    """Generate random password
    """
    return ''.join(random.choice(chars) for _ in range(size))
  
pass_string = "abcdefghkmnpqrstuwxyz123456789"
#for i in range(10):
    #print(password_generator(4, pass_string))
 
new_part_name = password_generator(4, pass_string)
 
# Connect to a running instance of Solid Edge
application = win32com.client.Dispatch("SolidEdge.Application")
 
# Get the documents collection
documents = application.Documents
 
# Set the path to the part file
part_file_path = os.path.join(os.getcwd(), "Part1.par")
 
# Open the part file
part = documents.Open(part_file_path)
#print(dir(part))
 
# Get the models collection
models = part.Models
#print(dir(models))
 
# Get the first model in the collection
model = models.Item(1)
#print(dir(model))
 
document = model.Document
#print(dir(document))
 
variables = document.Variables
 
# Get the variable you want to modify
width = variables.Item("Width")
length = variables.Item("Length")
height = variables.Item("Height")
 
# Set the new value for the variable in meter?
 
length.Value = random.SystemRandom().uniform(0.1, 0.3)
width.Value = random.SystemRandom().uniform(0.1, 0.3)
height.Value = random.SystemRandom().uniform(0.1, 0.3)
 
# Update the model to reflect the changes
#document.UpdateOnFileSave = True
model.Recompute()
 
# Set the path for the new file
new_file_path = os.path.join(os.getcwd(), new_part_name + ".par")
 
# Save the modified part to a new file
document.SaveAs(new_file_path)</pre>
<p>Modify assembly variables:</p>
<pre class="brush:py;auto-links:false;toolbar:false" contenteditable="false">import win32com.client
 
# Connect to a running instance of Solid Edge
application = win32com.client.Dispatch("SolidEdge.Application")
 
# Get the active assembly document
assembly_document = application.ActiveDocument
 
# Get the first occurrence in the assembly
occurrence = assembly_document.Occurrences.Item(1)
 
# Get the part document associated with the occurrence
part_document = occurrence.OccurrenceDocument
 
# Get the variables collection of the part document
variables = part_document.Variables
 
# Get a specific variable by its name
variable = variables.Item("VariableName")
 
# Modify the value of the variable
variable.Value = 10
 
# Update the assembly
assembly_document.Update()
</pre>
<p>Flask and Solid Edge:</p>
<pre class="brush:py;auto-links:false;toolbar:false" contenteditable="false">from flask import Flask, render_template, request
import win32com.client
 
app = Flask(__name__)
 
# Constants
filename = 'C:\\Path\\To\\YourFile.par'
 
@app.route('/', methods=['GET', 'POST'])
def index():
    if request.method == 'POST':
        new_length = float(request.form['length'])
 
        # Start Solid Edge
        application = win32com.client.Dispatch('SolidEdge.Application')
 
        # Open the document
        document = application.Documents.Open(filename)
 
        # Get the variables collection
        variables = document.Variables
 
        # Get the length variable
        length_variable = variables.Item('Length')
 
        # Set the new value
        length_variable.Value = new_length
 
        # Update the document
        document.Update()
 
        # Get the models collection
        models = document.Models
 
        # Get the first model
        model = models.Item(1)
 
        # Calculate the volume
        volume = model.ComputePhysicalProperties().Volume
 
        # Save the document
        document.Save()
 
        # Close the document
        document.Close()
 
        return render_template('index.html', volume=volume)
    else:
        return render_template('index.html')
 
if __name__ == '__main__':
    app.run()</pre>
<p>index.html</p>
<pre class="brush:html;auto-links:false;toolbar:false" contenteditable="false">&lt;!DOCTYPE html&gt;
&lt;html&gt;
    &lt;head&gt;
        &lt;title&gt;Solid Edge API&lt;/title&gt;
    &lt;/head&gt;
    &lt;body&gt;
        &lt;form method="post"&gt;
            &lt;label for="length"&gt;Length:&lt;/label&gt;
            &lt;input type="text" id="length" name="length"&gt;
            &lt;input type="submit" value="Submit"&gt;
        &lt;/form&gt;
        {% if volume %}
            &lt;p&gt;New volume: {{ volume }}&lt;/p&gt;
        {% endif %}
    &lt;/body&gt;
&lt;/html&gt;</pre>
<p>Create Part by api:</p>
<pre class="brush:py;auto-links:false;toolbar:false" contenteditable="false">import win32com.client
 
# Constants
filename = 'C:\\tmp\\new.par'
material_name = 'Steel'
 
# Start Solid Edge
application = win32com.client.Dispatch('SolidEdge.Application')
 
# Create a new part document
document = application.Documents.Add('SolidEdge.PartDocument')
# Get the ref planes collection
ref_planes = document.RefPlanes
'''
# Define the points
point1 = (0, 0, 0)
point2 = (100, 0, 0)
point3 = (0, 100, 0)
 
# Add the reference plane
ref_plane = ref_planes.AddBy3Points(point1, point2, point3)
'''
# Get the profile sets collection
profile_sets = document.ProfileSets
 
# Add a new profile set
objProfile = profile_sets.Add()
 
 
objP1 = objProfile.Points2d.Add(0, 0)
 
 
objP2 = objProfile.Points2d.Add(0.01, 0)
 
objP3 = objProfile.Points2d.Add(0, 0.01)
 
objEdgeSet[0] = objP1
 
 
objEdgeSet[1] = objP2
 
objEdgeSet[2] = objP3
objkeyPoints[0] = SolidEdgeConstants.KeyPointType.igKeyPointStart
 
 
objkeyPoints[1] = SolidEdgeConstants.KeyPointType.igKeyPointMiddle
 
objkeyPoints[2] = SolidEdgeConstants.KeyPointType.igKeyPointEnd
 
objNumEdges = 3
 
objRPNTC = document.RefPlanes.AddBy3Points(objNumEdges, objEdgeSet, objkeyPoints)
 
 
objRPNTC.Visible = True
# Save the document
document.Save()
 
# Close the document
document.Close()
'''
# Get the profile sets collection
profile_sets = document.ProfileSets
 
# Add a new profile set
profile_set = profile_sets.Add()
 
# Get the profiles collection
profiles = profile_set.Profiles
 
#print(dir(profiles))
 
application.DoIdle()
 
#Get a reference to the RefPlanes collection.
refPlanes = document.RefPlanes
print(dir(refPlanes))
 
#Get a reference to front RefPlane.
refPlane = refPlanes.GetFrontPlane()
 
# Add a new profile
profile = profiles.AddRef()
 
# Get the lines2d collection
lines2d = profile.Lines2d
 
# Draw a rectangle
line1 = lines2d.AddBy2Points(0, 0, 100, 0)
line2 = lines2d.AddBy2Points(100, 0, 100, 10)
line3 = lines2d.AddBy2Points(100, 10, 0, 10)
line4 = lines2d.AddBy2Points(0, 10, 0, 0)
 
# Define the profile as closed
profile.End(ProfileEndCap.Round)
 
# Get the models collection
models = document.Models
 
# Create an extruded protrusion
extruded_protrusion = models.AddProtrusionExtruded(profile_set, ProfilePlaneSide.PlaneSidePositive, ProfileEndCap.Round, 100)
 
# Get the materials collection
materials = document.Materials
 
# Get the steel material
material = materials.Item(material_name)
 
# Set the material of the model
model = models.Item(1)
model.Material = material
 
# Save the document
document.SaveAs(filename)
 
# Close the document
document.Close()
'''</pre>
<p>get part volume and save:</p>
<pre class="brush:py;auto-links:false;toolbar:false" contenteditable="false">import win32com.client
 
# Constants
filename = 'C:\\Path\\To\\YourFile.par'
new_length = 100.0
 
# Start Solid Edge
application = win32com.client.Dispatch('SolidEdge.Application')
 
# Open the document
document = application.Documents.Open(filename)
 
# Get the variables collection
variables = document.Variables
 
# Get the length variable
length_variable = variables.Item('Length')
 
# Set the new value
length_variable.Value = new_length
 
# Update the document
document.Update()
 
# Get the models collection
models = document.Models
 
# Get the first model
model = models.Item(1)
 
# Calculate the volume
volume = model.ComputePhysicalProperties().Volume
 
# Save the document
document.Save()
 
# Close the document
document.Close()
 
print(f'New volume: {volume}')</pre>
<p>Assembly example:</p>
<pre class="brush:py;auto-links:false;toolbar:false" contenteditable="false">import win32com.client
import os
 
# Connect to a running instance of Solid Edge
application = win32com.client.Dispatch("SolidEdge.Application")
 
# Get the documents collection
documents = application.Documents
 
# Set the path to the part file
assem_file_path = os.path.join(os.getcwd(), "Assem1.par")
 
# Open the part file
assembly= documents.Open(assem_file_path)
#print(dir(assembly))
 
# Get the occurrences collection
occurrences = assembly.Occurrences
 
# Get the first occurrence in the collection
occurrence = occurrences.Item(1)
 
document = occurrence.Document
 
# Get the variables collection
variables = document.Variables
 
# Get the variable you want to modify
my_variable = variables.Item("MyVariable")
 
# Set the new value for the variable
my_variable.Value = 50
 
# Update the model to reflect the changes
document.UpdateOnFileSave = True
 
# Set the path for the new file
new_file_path = os.path.join(os.getcwd(), "newAssem1.par")</pre>
<p>api cube with random new part filename:</p>
<pre class="brush:py;auto-links:false;toolbar:false" contenteditable="false">import win32com.client
import os
import random
import string
  
def password_generator(size=4, chars=string.ascii_lowercase + string.digits):
  
    """Generate random password
    """
    return ''.join(random.choice(chars) for _ in range(size))
  
pass_string = "abcdefghkmnpqrstuwxyz123456789"
#for i in range(10):
    #print(password_generator(4, pass_string))
 
new_part_name = password_generator(4, pass_string)
 
# Connect to a running instance of Solid Edge
application = win32com.client.Dispatch("SolidEdge.Application")
 
# Get the documents collection
documents = application.Documents
 
# Set the path to the part file
part_file_path = os.path.join(os.getcwd(), "Part1.par")
 
# Open the part file
part = documents.Open(part_file_path)
#print(dir(part))
 
# Get the models collection
models = part.Models
#print(dir(models))
 
# Get the first model in the collection
model = models.Item(1)
#print(dir(model))
 
document = model.Document
#print(dir(document))
 
variables = document.Variables
 
# Get the variable you want to modify
width = variables.Item("Width")
length = variables.Item("Length")
height = variables.Item("Height")
 
# Set the new value for the variable in meter?
 
length.Value = random.SystemRandom().uniform(0.1, 0.3)
width.Value = random.SystemRandom().uniform(0.1, 0.3)
height.Value = random.SystemRandom().uniform(0.1, 0.3)
 
# Update the model to reflect the changes
#document.UpdateOnFileSave = True
model.Recompute()
 
# Set the path for the new file
new_file_path = os.path.join(os.getcwd(), new_part_name + ".par")
 
# Save the modified part to a new file
document.SaveAs(new_file_path)</pre>
<p>Create Extrusion:</p>
<p>python -m win32com.client.makepy to interactively generate SolidEdgePart.py in C:\Users\Account\AppData\Local\Temp\gen_py\3.11</p>
<p><a href="https://nfuedu-my.sharepoint.com/:u:/g/personal/yen_nfu_edu_tw/EdIojU-TIEZOqAkpm4OCB5wBKo-XipJQ-t_LJ8-8eXCuJw?e=fGrOaQ">SolidEdgePart_create_extrusion_example.7z</a> (for Solid Edge version 2210 and downloaded for @nfu users only)</p>
<pre class="brush:py;auto-links:false;toolbar:false" contenteditable="false">import win32com.client
import SolidEdgePart
 
# Start Solid Edge
application = win32com.client.Dispatch("SolidEdge.Application")
 
# Make the application visible
application.Visible = True
 
# Create a new part document
partDocument = application.Documents.Add("SolidEdge.PartDocument")
 
# Get the refPlanes collection
refPlanes = partDocument.RefPlanes
 
# Get the top plane
topPlane = refPlanes.Item(3)
 
# Add a new sketch on the top plane
sketch = partDocument.Sketches.AddByPlane(topPlane)
 
# Get the profile
profile = sketch.Profiles.Add(topPlane)
 
# Draw a circle with center at (0,0) and radius 0.05
circle = profile.Circles2d.AddByCenterRadius(0, 0, 0.05)
 
# Close the profile
profile.End(2)
 
# Define the extrusion parameters
extrusionDistance = "0.1"
extrusionDirection = SolidEdgePart.constants.igRight
 
# Create the extrusion using AddFiniteExtrudedProtrusion
extrusion = partDocument.Models.AddFiniteExtrudedProtrusion(1, [profile], extrusionDirection, extrusionDistance)
 
# Save the part file
partDocument.SaveAs(r"C:\Path\To\PartFile.par")</pre>
<pre class="brush:py;auto-links:false;toolbar:false" contenteditable="false">import win32com.client
import SolidEdgePart
 
# Start Solid Edge
application = win32com.client.Dispatch("SolidEdge.Application")
 
# Make the application visible
application.Visible = True
 
# Create a new part document
partDocument = application.Documents.Add("SolidEdge.PartDocument")
 
# Get the refPlanes collection
refPlanes = partDocument.RefPlanes
 
# Get the top plane
topPlane = refPlanes.Item(3)
 
# Add a new sketch on the top plane
sketch = partDocument.Sketches.AddByPlane(topPlane)
 
# Get the profile
profile = sketch.Profiles.Add(topPlane)
 
# Draw the outer rectangle of the link using four lines
line1 = profile.Lines2d.AddBy2Points(-0.1, -0.05, 0.1, -0.05)
line2 = profile.Lines2d.AddBy2Points(0.1, -0.05, 0.1, 0.05)
line3 = profile.Lines2d.AddBy2Points(0.1, 0.05, -0.1, 0.05)
line4 = profile.Lines2d.AddBy2Points(-0.1, 0.05, -0.1, -0.05)
 
# Draw the first hole
circle1 = profile.Circles2d.AddByCenterRadius(-0.05, 0, 0.02)
 
# Draw the second hole
circle2 = profile.Circles2d.AddByCenterRadius(0.05, 0, 0.02)
 
# Close the profile
profile.End(2) # 2 corresponds to igProfileClosed
 
# Define the extrusion parameters
extrusionDistance = 0.1
extrusionDirection = SolidEdgePart.constants.igRight
 
# Create the extrusion using AddFiniteExtrudedProtrusion
extrusion = partDocument.Models.AddFiniteExtrudedProtrusion(1, [profile], extrusionDirection, extrusionDistance)
 
# fix according to https://community.sw.siemens.com/s/question/0D54O000061xsuMSAQ/circle-extrusion-problem</pre>
<p>參考:</p>
<p style="padding-left: 30px;"><a href="https://nfuedu-my.sharepoint.com/:b:/g/personal/yen_nfu_edu_tw/EZLh-WxUQalCsEevZZYg5j4BWKeqLa1CkTukFFg7yyIArA?e=nctqWp">Solid Edge Programming Guide.pdf</a> (for @nfu users only)</p>
<p style="padding-left: 30px;"><a href="https://nfuedu-my.sharepoint.com/:u:/g/personal/yen_nfu_edu_tw/EcRdddi5q7NBtwfVidgXoRUBmakACONd_q1xuUAzWZmdkg?e=8WmybY">Solid Edge Type Library for Python.7z</a> (for @nfu users only)</p>
<br />MCAD << <a href='MCAD.html'>Previous</a> <a href='Tasks.html'>Next</a> >> Tasks</div>
        
    <!-- footer -->
      <div class="container">
        <div class="row pt-3 mx-auto">
            <p>
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank" >Colorlib</a>
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            </p>
        </div>
      </div>
    <!-- for footer -->
    
        </div> <!-- for site wrap -->
            <!-- <script src="../cmsimde/static/chimper/js/jquery-3.3.1.min.js"></script> -->
            <script src="../cmsimde/static/chimper/js/jquery-migrate-3.0.1.min.js"></script>
            <script src="../cmsimde/static/chimper/js/jquery-ui.js"></script>
            <script src="../cmsimde/static/chimper/js/popper.min.js"></script>
            <script src="../cmsimde/static/chimper/js/bootstrap.min.js"></script>
            <script src="../cmsimde/static/chimper/js/owl.carousel.min.js"></script>
            <script src="../cmsimde/static/chimper/js/jquery.stellar.min.js"></script>
            <script src="../cmsimde/static/chimper/js/jquery.countdown.min.js"></script>
            <script src="../cmsimde/static/chimper/js/jquery.magnific-popup.min.js"></script>
            <script src="../cmsimde/static/chimper/js/bootstrap-datepicker.min.js"></script>
            <script src="../cmsimde/static/chimper/js/aos.js"></script>
            <!--
            <script src="../cmsimde/static/chimper/js/typed.js"></script>
                    <script>
                    var typed = new Typed('.typed-words', {
                    strings: ["Web Apps"," WordPress"," Mobile Apps"],
                    typeSpeed: 80,
                    backSpeed: 80,
                    backDelay: 4000,
                    startDelay: 1000,
                    loop: true,
                    showCursor: true
                    });
                    </script>
            -->
            <script src="../cmsimde/static/chimper/js/main.js"></script>
        
<!-- 啟用 LaTeX equations 編輯 -->
  <!-- <script>
  MathJax = {
    tex: {inlineMath: [['$', '$'], ['\(', '\)']]}
  };
  </script>
  <script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js"></script>-->
    </body></html>
        